### ISSUE TITLE
Continue after failed job (collect output)

### ISSUE THREAD

**Issue by hannesa2** [Malinskiy/action-android#19]
I've a matrix job with Espresso and I want collect the output

      - name: Run instrumentation tests api ${{ matrix.android-api }}
        uses: malinskiy/action-android/emulator-run-cmd@release/0.0.5
        with:
          cmd: ./gradlew cAT --stacktrace
          api: ${{ matrix.android-api }}
          tag: default
          abi: x86
      - name: Archive Espresso results api ${{ matrix.android-api }}
        uses: actions/upload-artifact@v1
        with:
          name: Espresso-report
          path: owncloudApp/build/reports/androidTests/connected 

But when the Espresso job fails, the following jobs (and the result collecting one) are canceled , that's why no output is collected.
<img width="274" alt="image" src="https://user-images.githubusercontent.com/3314607/74708939-36cb2180-521e-11ea-8909-9b245a1b5472.png">

How to archive such a workflow ?

I could skip the matrix way, but I want to have the test result.

**Comment by hannesa2** [comment]
I found an ugly workaround. 
When you use 
`uses: malinskiy/action-android/emulator-run-cmd@release/0.0.3`
it will ignore failure and collect output.

What's about to include 
`uses: actions/upload-artifact@v1` in this action, then the artifacts could be collected on any case. A follow up failure is then no issue anymore

**Comment by hannesa2** [comment]
Or what's about to add something like this

![image](https://user-images.githubusercontent.com/3314607/80344812-79d1f280-8868-11ea-9a14-66c2f61eaf41.png)

To have a choice, if failing Espresso test should fail complete action.

Sorry, I've no clue, how to do this, otherwise I would make a PR

**Comment by Malinskiy** [comment]
@hannesa2  Feel free to use https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontinue-on-error for this setup. This is not specific for this action, just a general GH Actions setup
