### ISSUE TITLE
Failed to run sdkmanager

### ISSUE THREAD

**Issue by Glusk2** [Malinskiy/action-android#2]
I've this [build](https://github.com/Glusk2/sprouts/commit/70b70a491eb91924ad966eeb6ac4a237cfaf3c98/checks?check_suite_id=287133766#step:6:14) that uses `instal-sdk` action.

There seems to be something wrong with running:

``` bash
.$ANDROID_HOME/tools/bin/sdkmanager "platforms;android-28" "platform-tools" "build-tools;28.0.3"
```

I've first tried (note the added slash after the dot):
``` bash
./$ANDROID_HOME/tools/bin/sdkmanager "platforms;android-28" "platform-tools" "build-tools;28.0.3"
```

What seems to be the issue here? How do I run this?

**Comment by Glusk2** [comment]
It turns out I have to ommit both `/` and `.`. This is how it works:
``` bash
$ANDROID_HOME/tools/bin/sdkmanager ...
```

**Comment by Malinskiy** [comment]
Hey @Glusk2 
The `.$ANDROID_HOME` and `./$ANDROID_HOME` are resolved as relative paths to the current directory.
Unless you're in `/` you have to use either absolute path `$ANDROID_HOME/tools/bin/sdkmanager` as you mentioned or just `sdkmanager` since the action modifes the PATH envvar.
