### ISSUE TITLE
Breaks with AGP7

### ISSUE THREAD

**Issue by kurtisnelson** [Malinskiy/action-android#33]
Per Googlers, there is now a package called `cmdline-tools` that should be used for installing things with AGP7.

**Comment by Malinskiy** [comment]
@kurtisnelson thanks for bringing this up. I'll test the new plugin on a separate branch

**Comment by kurtisnelson** [comment]
Additionally, Java 11 will be required going forward. Google is going to update the release notes hopefully by next week.

**Comment by Malinskiy** [comment]
The java setup is probably outside of this action: I'd expect people to use [setup-java](https://github.com/actions/setup-java).

I'll update the action to use the latest cmdline-tools package and hope that it doesn't change the directory structure in the near future.

**Comment by Malinskiy** [comment]
Released in `0.1.0`.  Please test and message me if there are any problems

**Comment by kurtisnelson** [comment]
Verified.
