### ISSUE TITLE
RunCMD default tag is not "default"

### ISSUE THREAD

**Issue by Octav14n** [Malinskiy/action-android#38]
Emulator Run CMD does not default to "default" tag.
it outputs `Unknown tag ${tag}. Using default` in line 22 but in the next line sets `tag = 'google_apis'`

I expected line 23 to be `tag = 'default'`
Alternately I expected the message in line 22 to inform me that `google_apis` will be used as `tag`.

https://github.com/Malinskiy/action-android/blob/2e4591be80bdbe897c601bd89046582f28e7d603/emulator-run-cmd/src/main.ts#L20-L24

**Comment by Malinskiy** [comment]
Thanks for the issue!
Fixed in 0.1.2
