### ISSUE TITLE
Is it possible to have this action cache the installation and emulator?

### ISSUE THREAD

**Issue by ZacSweers** [Malinskiy/action-android#4]
GitHub actions has formal caching support now, would be great if it's possible to (partially) cache some of the downloaded portions of this action with it.

https://github.com/actions/cache

**Comment by Malinskiy** [comment]
@ZacSweers Right now the url for sdk doesn't contain the actual version of sdk components, it's just a minimal setup of android sdk. We can ofc cache this. I'll provide an example config soon.

The caching is not part of the action though and really depends on what you're trying to cache and how you can create a unique key for it so it's quite hard to list all the possible cases that are related to this action. If you have other cases - feel free to suggest them though.

**Comment by Malinskiy** [comment]
Hey @ZacSweers,
I've tried to use the cache for the android-sdk but unfortunately [it's over the size limit of the cache entry](https://github.com/Malinskiy/action-android/commit/1eb7d55ef7556b2d0d121a9c57c8a01ebc2016ed/checks?check_suite_id=322202197)

The size of the installation is too large :(

**Comment by Malinskiy** [comment]
I'm gonna close this issue for the time being. Feel free to reopen if there are gonna be changes to cache limit size and we can reevaluate caching dependencies of this action

**Comment by ZacSweers** [comment]
They've raised it to 2GB, possible to reconsider?
