### ISSUE TITLE
getting stuck at license prompts

### ISSUE THREAD

**Issue by hoff2-ACN** [Malinskiy/action-android#5]
SDK licenses have changed since version 25 so the hashes being written during installation don't match when trying to use with newer versions (28 in our case).

**Comment by Malinskiy** [comment]
Hey @hoff2-ACN 
The 0.0.3 works ok with emulators up to [29](https://github.com/Malinskiy/adam/runs/315665159). Anything I missed here?

Here is a list of all current license files that are created if you use `sdkmanager --licenses` on MacOS:

```bash
➜  licenses find . -type f | xargs cat

24333f8a63b6825ea9c5514f83c2829b004d1fee
84831b9409646a918e30573bab4c9c91346d8abd
e9acab5b5fbb560a72cfaecce8946896ff6aab9d
601085b94cd77f0b54ff86406957099ebe79c4d6
33b6a2b64607f11b759f320ef9dff4ae5c47d97a
d975f751698a77b662f1254ddbeed3901e976f5a
859f317696f67ef3d7f30a50a5560e7834b43903%                                                                                                                                                                                                   ➜  licenses tree
.
├── android-googletv-license
├── android-sdk-arm-dbt-license
├── android-sdk-license
├── android-sdk-preview-license
├── google-gdk-license
├── intel-android-extra-license
└── mips-android-sysimage-license

0 directories, 7 files
```

**Comment by hoff2-ACN** [comment]
That's what I have on my local machine right now as well but my actions kept getting stuck at a licensing prompt nonetheless and I did see some different hashes than these at some point, but over the holiday I lost track of that info. I'll look further. Can also confirm that the `yes |` method in #8 works for me.

**Comment by hoff2-ACN** [comment]
Ah, We both have `859f317696f67ef3d7f30a50a5560e7834b43903` but I don't see that one in [here](https://github.com/Malinskiy/action-android/blob/master/install-sdk/src/sdk.ts#L84)

**Comment by Malinskiy** [comment]
This one is for the `android-sdk-arm-dbt-license`, probably a previous version. I'll add it to the list

**Comment by Malinskiy** [comment]
@hoff2-ACN does this still happen for you?

**Comment by hoff2-ACN** [comment]
@Malinskiy haven't looked at this in a while but I believe your addition resolved it. Thanks!

**Comment by Malinskiy** [comment]
Feel free to reopen the issue if this reappears
