### ISSUE TITLE
New version ?

### ISSUE THREAD

**Issue by hannesa2** [Malinskiy/action-android#65]
Hi, 
thanks for merging https://github.com/Malinskiy/action-android/pull/59 , but what's about to merge **my** remaining  pull requests and **all** other version bump pull requests and create a new release ?
This would help us all ! Thank you

**Comment by RohovDmytro** [comment]
Yes. Please.

**Comment by Malinskiy** [comment]
https://github.com/Malinskiy/action-android/releases/tag/0.1.3
