### ISSUE TITLE
Update to node20

### ISSUE THREAD

**Issue by yukilabo** [Malinskiy/action-android#84]
Please update your script to Node 20.

Node 16 is being deprecated, and the following warning is being displayed in the GitHub Actions logs:

"Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: malinskiy/action-android/install-sdk@release/0.1.6, malinskiy/action-android/emulator-run-cmd@release/0.1.6. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/."

**Comment by Malinskiy** [comment]
PRs are welcome. Thanks
